cart app/urls.py
from django.urls import re_path
from .views import cart_detail, cart_add, cart_remove

app_name = 'cart' # имя приложения

# маршрутизаторы
# routers
urlpatterns = [
    re_path(r'^$', cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<toy_id>\d+)/$', cart_add, name='cart_add'),
    re_path(r'^remove/(?P<toy_id>\d+)/$', cart_remove, name='cart_remove'),
]

settings+urls/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.conf import settings
from django.conf.urls.static import static

# список путей, ведущих к приложениям сайта
# list of paths leading to site applications
urlpatterns = [
    re_path(r'^admin/', admin.site.urls),         # путь к страничке администрации сайта; path to the site administration page
    re_path(r'^toys/', include('toys.urls')),     # путь к приложению toys; path to toys app
    re_path(r'^cart/', include('cart.urls')),     # путь к приложению cart; path to cart app
    re_path(r'^orders/', include('orders.urls')), # путь к приложению orders; path to orders app
]

# использование статических файлов(изображения для игрушек), если DEBUG = True
# use static files (images for toys) if DEBUG = True
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

toys app/urls.py
from django.urls import re_path
from toys.views import toy_list, toy_detail

app_name = 'toys' # имя приложения

# пути к методам из файла views
# paths to methods from the views file
urlpatterns = [
    re_path(r'^$', toy_list, name='all_toys'),
    re_path(r'^(?P<typ_slug>[-\w]+)/$', toy_list, name='toys_by_type'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', toy_detail, name='toy_detail'),
]

toys app/models.py
from django.db import models
from django.urls import reverse


# null - если True, то поле в таблице базы данных может хранить значение null
# blank - если True, то Django позволит занести в поле пустое значение
# db_index - если True, то по текущему полю в таблице будет создан индекс
# default - значение по умолчанию, записываемое в поле, если значение не внесено


# классы для создания колонок в базе данных; classes for creating columns in the database
# вторичная таблица; secondary table
class Toy(models.Model):
    name = models.CharField(max_length=30, verbose_name='Название игрушки')
    content = models.TextField(null=True, blank=True, verbose_name='Описание')
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, verbose_name='Изображение')
    slug = models.SlugField(max_length=60, null=True, blank=True, db_index=True, verbose_name='Ссылка')
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Цена')
    stock = models.PositiveIntegerField(null=True, verbose_name='Количество')                                 # количество товара
    available = models.BooleanField(default=True, verbose_name='В наличии')                                   # доступность товара
    created = models.DateTimeField(auto_now_add=True, null=True, db_index=True, verbose_name='Дата создания')
    updated = models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')
    typ = models.ForeignKey('Typ', null=True, on_delete=models.PROTECT, verbose_name='Тип игрушки')           # связь один ко многим; one to many

    # опции модели Toy; Toy model options
    class Meta:
        verbose_name = 'Игрушка'
        verbose_name_plural = 'Игрушки'
        ordering = ['name']
        index_together = (('id', 'slug'),)

    # строковое представление модели; string representation of the model
    def __str__(self):
        return self.name
    
    # метод получения абсолютного значения ссылки; representing a reference to an object in a database
    def get_absolute_url(self):
        return reverse('toys:toy_detail', args=[self.id, self.slug])


# первичная таблица; primary table
class Typ(models.Model):
    name = models.CharField(max_length=30, verbose_name='Название типа игрушки')
    slug = models.SlugField(max_length=200, null=True, db_index=True, unique=True, verbose_name='Ссылка')

    # опции модели Typ; Typ model options
    class Meta:
        verbose_name = 'Тип игрушки'
        verbose_name_plural = 'Типы игрушек'
        ordering = ['name']

    # строковое представление модели; string representation of the model
    def __str__(self):
        return self.name
    
    # представление ссылки на объект в базе данных; representing a reference to an object in a database
    def get_absolute_url(self):
        return reverse('toys:toys_by_type', args=[self.slug])

toys app/views.py
from django.shortcuts import render, get_object_or_404
from toys.models import Toy, Typ
from cart.forms import CartAddProductForm # подключение формы для добавления игрушки в корзину; connecting a form to add a toy to the cart


 # метод вывода информации о доступных игрушках; method for displaying information about available toys
def toy_list(request, typ_slug=None):
    toy = Toy.objects.filter(available=True)
    types = Typ.objects.all()
    typ = None
    if typ_slug:
        typ = get_object_or_404(Typ, slug=typ_slug)
        toy = toy.filter(typ=typ)
    context = {'toy': toy, 'typ': typ, 'types': types}
    return render(request, 'toys/toys1.html', context)


# метод отображения сведений об игрушке; method for displaying toy details
def toy_detail(request, id, slug):
    toy = get_object_or_404(Toy, id=id, slug=slug, available=True)
    cart_toy_form = CartAddProductForm()
    context = {'toy': toy, 'cart_toy_form': cart_toy_form}
    return render(request, 'toys/toys1_detail.html', context)

templates/toys app/toys.html
<!DOCTYPE html>
<html>
    {% extends "layout/basic.html" %}
    {% load static %}
    {% block content %}
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Yami Toys{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'toys/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'toys/toys.css' %}">
    </head>
    <body>
      <h1 class="h_1">игрушки</h1>
      <div class="sidebar">
          <a class="link1" href="{% url 'toys:all_toys' %}">все</a>
        {% for tp in types %}
          <p><a class="link1" href="{{ tp.get_absolute_url }}">{{ tp.name }}</a></p>
        {% endfor %}
      </div>
      <div class="container">
          <div class="row">
            {% for ty in toy %}
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
              <div class="block">
                <a class="link1" href="{{ ty.get_absolute_url }}">
                  <img class='image' src="{% if ty.image %} {{ ty.image.url }} {% else %} {% static 'img/PUPA2.gif' %} {% endif %}" height="450" width="350">
                </a>
                <a class="link1" href="{{ ty.get_absolute_url }}">{{ ty.name }}</a><br>
                <p class="toy"><b>${{ ty.price }}</b></p>
              </div>
            </div>
            {% endfor %}
          </div>
      </div>
    {% endblock %}
    </body>
</html>

templates/toys app/toys1.html
<!DOCTYPE html>
<html>
    {% extends "layout/main1.html" %}
    {% load static %}
    {% block content %}
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Yami Toys{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'toys/bootstrap1.css' %}">
        <link rel="stylesheet" href="{% static 'toys/style2.css' %}">
    </head>
    <body>
      <h1 class="h_1">игрушки</h1>
      <div class="container">
          <div class="row">
            {% for ty in toy %}
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
              <div class="block">
                <a class="link1" href="{{ ty.get_absolute_url }}">
                  <img class='image' src="{% if ty.image %} {{ ty.image.url }} {% else %} {% static 'img/PUPA2.gif' %} {% endif %}" height="450" width="350">
                </a>
                <a class="link1" href="{{ ty.get_absolute_url }}">{{ ty.name }}</a><br>
                <p class="toy"><b>{{ ty.price }}$$$</b></p>
              </div>
            </div>
            {% endfor %}
          </div>
      </div>
    {% endblock %}
    </body>
</html>

templates/toys app/toys1_detail.html
<!DOCTYPE html>
<html>
    {% extends "layout/basic.html" %}
    {% load static %}
    {% block content %}
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Yami Toys{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'toys/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'toys/toys_detail.css' %}">
    </head>
    <body>
        <h1 class="h_1">игрушки</h1>
        <div class="container">
            <div class="row">
              <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div class="block">
                  <img class="image" src="{% if toy.image %} {{ toy.image.url }} {% else %} {% static 'img/PUPA2.gif' %} {% endif %}" height="450" width="350">
                  <h2 class="h_2">{{ toy.name }}</h2>
                  <a class="link1" href="{{ toy.typ.get_absolute_url }}">{{ toy.typ }}</a>
                  <p class="toy"><b>{{ toy.content }}</b></p>
                  <p class="toy"><b>{{ toy.price }}$$$</b></p>
                  <form action="{% url 'cart:cart_add' toy.id %}" method="post">
                    <b>{{ cart_toy_form }}
                    {% csrf_token %}</b>
                    <input type="submit" value="добавить">
                  </form>
                </div>
              </div>
            </div>
        </div>
    </body>
    {% endblock %}
</html>

templates/toys app/toys_detail.html
<!DOCTYPE html>
<html>
    {% extends "layout/basic.html" %}
    {% load static %}
    {% block content %}
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Yami Toys{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'toys/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'toys/toys_detail.css' %}">
    </head>
    <body>
        <h1 class="h_1">игрушки</h1>
        <div class="container">
            <div class="row">
              <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div class="block">
                  <img class="image" src="{% if toy.image %} {{ toy.image.url }} {% else %} {% static 'img/PUPA2.gif' %} {% endif %}" height="450" width="350">
                  <h2 class="h_2">{{ toy.name }}</h2>
                  <a class="link1" href="{{ toy.typ.get_absolute_url }}">{{ toy.typ }}</a>
                  <p class="toy"><b>{{ toy.content }}</b></p>
                  <p class="toy"><b>${{ toy.price }}</b></p>
                  <form action="{% url 'cart:cart_add' toy.id %}" method="post">
                    <b>{{ cart_toy_form }} {% csrf_token %}</b> 
                    <input type="submit" value="добавить">
                  </form>
                </div>
              </div>
            </div>
        </div>
    </body>
    {% endblock %}
</html>