cart app/urls.py
from django.urls import re_path
from .views import cart_detail, cart_add, cart_remove

app_name = 'cart' # имя приложения

# маршрутизаторы
# routers
urlpatterns = [
    re_path(r'^$', cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<toy_id>\d+)/$', cart_add, name='cart_add'),
    re_path(r'^remove/(?P<toy_id>\d+)/$', cart_remove, name='cart_remove'),
]

settings+urls/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.conf import settings
from django.conf.urls.static import static

# список путей, ведущих к приложениям сайта
# list of paths leading to site applications
urlpatterns = [
    re_path(r'^admin/', admin.site.urls),         # путь к страничке администрации сайта; path to the site administration page
    re_path(r'^toys/', include('toys.urls')),     # путь к приложению toys; path to toys app
    re_path(r'^cart/', include('cart.urls')),     # путь к приложению cart; path to cart app
    re_path(r'^orders/', include('orders.urls')), # путь к приложению orders; path to orders app
]

# использование статических файлов(изображения для игрушек), если DEBUG = True
# use static files (images for toys) if DEBUG = True
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

toys app/urls.py
from django.urls import re_path
from toys.views import toy_list, toy_detail

app_name = 'toys' # имя приложения

# пути к методам из файла views
# paths to methods from the views file
urlpatterns = [
    re_path(r'^$', toy_list, name='all_toys'),
    re_path(r'^(?P<typ_slug>[-\w]+)/$', toy_list, name='toys_by_type'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', toy_detail, name='toy_detail'),
]

templates/basic.html
<!DOCTYPE html>
<html>
    {% load static %}
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Main Yami Toys{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'toys/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'toys/basic.css' %}">
    </head>
    <body>
        <div class="menu">
            <button onclick="myFunction()" class="menubtn">menu</button>
            <div id="mymenu" class="menu-content">
              <a href="{% url 'toys:all_toys' %}">игрушки</a><br>
              <a href="{% url 'cart:cart_detail' %}">корзина</a><br>
            </div>
        </div>
        <div class="cart_block">
          {% with total_items=cart|length %}
            {% if cart|length > 0 %}
              <a class="link1" href="{% url 'cart:cart_detail' %}">корзина
              <img class="img3" src="{% static 'img/treeleaf1.gif'%}" height="50" width="50"><br>{{ total_items }} item{{ total_items|pluralize }} ${{ cart.get_total_price }}</a>
            {% else %}
              <a class="link2" href="{% url 'cart:cart_detail' %}">корзина пустая <img class="img3" src="{% static 'img/treeleaf1.gif'%}" height="50" width="50"></a>
            {% endif %}
          {% endwith %}
        </div>
        <img class="img1" src="{% static 'img/love1.gif' %}">
        <script>
            function myFunction() {
                document.getElementById("mymenu").classList.toggle("show");
            }
          
            window.onclick = function(event) {
              if (!event.target.matches('.menubtn')) {
            
                var dropdowns = document.getElementsByClassName("menu-content");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                  var openDropdown = dropdowns[i];
                  if (openDropdown.classList.contains('show')) {
                    openDropdown.classList.remove('show');
                  }
                }
              }
            }
        </script>
        {% block content %}
        {% endblock %}<br><br>
        <a class="link3" href="https://mail.google.com/mail/" target="_blank">mailbox: yamitoys@gmail.com</a>
        <div class="container">
          <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
              <div class="block">
                  <img class='img2' src="{% static 'img/flower2.gif' %}" height="175" width="350">
              </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
              <div class="block">
                  <img class='img2' src="{% static 'img/flower2.gif' %}" height="175" width="350">
              </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
              <div class="block">
                  <img class='img2' src="{% static 'img/flower2.gif' %}" height="175" width="350">
              </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
              <div class="block">
                  <img class='img2' src="{% static 'img/flower2.gif' %}" height="175" width="350">
              </div>
            </div>
          </div>
        </div>
    </body>
</html>

templates/main1.html
<!DOCTYPE html>
<html>
    {% load static %}
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Main Yami Toys{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'toys/bootstrap1.css' %}">
        <link rel="stylesheet" href="{% static 'toys/main1.css' %}">
    </head>
    <body>
        <div class="menu">
            <button onclick="myFunction()" class="menubtn">menu</button>
            <div id="mymenu" class="menu-content">
              <a href="{% url 'toys:all_toys' %}">игрушки</a><br>
              <a href="{% url 'cart:cart_detail' %}">корзина</a><br>
            </div>
        </div>
        <div class="cart_block">
          {% with total_items=cart|length %}
            {% if cart|length > 0 %}
              корзина: 
              <a class="lnk" href="{% url 'cart:cart_detail' %}"><b>{{ total_items }} item{{ total_items|pluralize }},{{ cart.get_total_price }}$$$</b></a>
            {% else %}
              <a class="lnk" href="{% url 'cart:cart_detail' %}"><b>корзина пустая</b></a>
            {% endif %}
          {% endwith %}
        </div>
        <img class="img1" src="{% static 'img/love1.gif' %}">
        <script>
            function myFunction() {
                document.getElementById("mymenu").classList.toggle("show");
            }
          
            window.onclick = function(event) {
              if (!event.target.matches('.menubtn')) {
            
                var dropdowns = document.getElementsByClassName("menu-content");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                  var openDropdown = dropdowns[i];
                  if (openDropdown.classList.contains('show')) {
                    openDropdown.classList.remove('show');
                  }
                }
              }
            }
        </script>
        {% block content %}
        {% endblock %}<br><br>
        <a class="link" href="https://mail.google.com/mail/" target="_blank">mailbox: yamitoys@gmail.com</a>
        <div class="container">
          <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
              <div class="block">
                  <img class='image' src="{% static 'img/flower2.gif' %}" height="175" width="350">
              </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
              <div class="block">
                  <img class='image' src="{% static 'img/flower2.gif' %}" height="175" width="350">
              </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
              <div class="block">
                  <img class='image' src="{% static 'img/flower2.gif' %}" height="175" width="350">
              </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
              <div class="block">
                  <img class='image' src="{% static 'img/flower2.gif' %}" height="175" width="350">
              </div>
            </div>
          </div>
      </div>
    </body>
</html>