cart app/urls.py
from django.urls import re_path
from .views import cart_detail, cart_add, cart_remove

app_name = 'cart' # имя приложения

# маршрутизаторы
# routers
urlpatterns = [
    re_path(r'^$', cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<toy_id>\d+)/$', cart_add, name='cart_add'),
    re_path(r'^remove/(?P<toy_id>\d+)/$', cart_remove, name='cart_remove'),
]

orders app/urls.py
from django.urls import re_path
from . import views

app_name = 'orders'

urlpatterns = [
    re_path(r'^create/$', views.order_create, name='order_create'), # путь к представлению приложения orders
]

settings+urls/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.conf import settings
from django.conf.urls.static import static

# список путей, ведущих к приложениям сайта
# list of paths leading to site applications
urlpatterns = [
    re_path(r'^admin/', admin.site.urls),         # путь к страничке администрации сайта; path to the site administration page
    re_path(r'^toys/', include('toys.urls')),     # путь к приложению toys; path to toys app
    re_path(r'^cart/', include('cart.urls')),     # путь к приложению cart; path to cart app
    re_path(r'^orders/', include('orders.urls')), # путь к приложению orders; path to orders app
]

# использование статических файлов(изображения для игрушек), если DEBUG = True
# use static files (images for toys) if DEBUG = True
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

cart app/forms.py
from django import forms

# количесво возможного выбора игрушек при помещении игрушки в корзину
# number of possible choice of toys when placing a toy in the cart
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


# форма; form
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from toys.models import Toy
from .cart import Cart
from .forms import CartAddProductForm


# метод получения запроса и номера игрушки и добавление ее в корзину
# method for receiving the request and the number of the toy and adding it to the cart
@require_POST
def cart_add(request, toy_id):
    cart = Cart(request)
    toy = get_object_or_404(Toy, id=toy_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(toy=toy,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail') # перенаправление к деталям корзины


# метод удаление игрушки из корзины
# method for removing a toy from the cart
def cart_remove(request, toy_id):
    cart = Cart(request)
    toy = get_object_or_404(Toy, id=toy_id)
    cart.remove(toy)
    return redirect('cart:cart_detail')


# детали корзины
# cart details
def cart_detail(request):
    cart = Cart(request)
    context = {'cart': cart}
    return render(request, 'cart/cart1.html', context)

templates/cart app/cart.html
<!DOCTYPE html>
<html>
    {% extends "layout/basic.html" %}
    {% load static %}
    {% block content %}
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Yami Cart{% endblock %}</title>
        <link rel="stylesheet" hraf="{% static 'cart/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'cart/cart.css' %}">
    </head>
    <body>
        <h1 class="h_1">корзина</h1>
        <div class="container">
          <div class="row">
            {% for item in cart %}
              {% with t=item.toy %}
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                  <div class="block">
                    <a href="{{ t.get_absolute_url }}">
                      <img class="image" src="{% if t.image %} {{ t.image.url }} {% else %} {% static 'img/PUPA2.gif' %} {% endif %}" height="450" width="350">
                    </a>
                    <h2 class="h_2">{{ t.name }}</h2>
                    <p class="toy"><b>количество: {{ item.quantity }}</b></p>
                    <a class="link1" href="{% url 'cart:cart_remove' t.id %}">удалить</a>
                    <p class="toy"><b>цена за 1: ${{ item.price }}</b></p>
                    <p class="toy"><b>общая цена: ${{ item.total_price }}</b></p>
                  </div>
                </div>
              {% endwith %}
            {% endfor %}
          </div>
        </div>
        <p class="p1">общая сумма = ${{ cart.get_total_price }}</p>
        <a href="{% url 'orders:order_create' %}" class="link3">оформить покупку</a>
    </body>
    {% endblock %}
</html>

templates/cart app/cart1.html
<!DOCTYPE html>
<html>
    {% extends "layout/main1.html" %}
    {% load static %}
    {% block content %}
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Yami Cart{% endblock %}</title>
        <link rel="stylesheet" hraf="{% static 'cart/bootstrap1.css' %}">
        <link rel="stylesheet" href="{% static 'cart/cart2.css' %}">
    </head>
    <body>
        <h1 class="h_1">корзина</h1>
        <div class="container">
          <div class="row">
            {% for item in cart %}
              {% with t=item.toy %}
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                  <div class="block">
                    <a href="{{ t.get_absolute_url }}">
                      <img class="image" src="{% if t.image %} {{ t.image.url }} {% else %} {% static 'img/PUPA2.gif' %} {% endif %}" height="450" width="350">
                    </a>
                    <h2 class="h_2">{{ t.name }}</h2>
                    <p class="toy"><b>количество: {{ item.quantity }}</b></p>
                    <a class="link1" href="{% url 'cart:cart_remove' t.id %}">удалить</a>
                    <p class="toy"><b>цена за 1: {{ item.price }}$$$</b></p>
                    <p class="toy"><b>общая цена: {{ item.total_price }}$$$</b></p>
                  </div>
                </div>
              {% endwith %}
            {% endfor %}
          </div>
        </div>
        <p class="p1">общая сумма = {{ cart.get_total_price }}$$$</p>
    </body>
    {% endblock %}
</html>